<?php
require_once(drupal_get_path('module', 'facilities') . '/facilities_constants.php');
require_once(drupal_get_path('module', 'facilities') . '/facilities_api.inc');

function facilities_menu() {
	$items[FACILITIES_MODULE_NAME. '/view'] = array(
		'title' => t('Browse Facilities'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('facilities_view_room'),
		'access callback' => 'logged_in',
		'file' => 'facilities_list.inc',
		'type' => MENU_NORMAL_ITEM
	);

	$items[FACILITIES_MODULE_NAME . '/view/room'] = array(
		'title' => t('Rooms'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('facilities_view_room'),
		'access callback' => 'logged_in',
		'file' => 'facilities_list.inc',
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'weight' => 0,
	);

	$items[FACILITIES_MODULE_NAME . '/view/bbq'] = array(
		'title' => t('BBQ Pits'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('facilities_view_bbq'),
		'access callback' => 'logged_in',
		'file' => 'facilities_list.inc',
		'type' => MENU_LOCAL_TASK,
		'weight' => 1
	);

	$items[FACILITIES_MODULE_NAME . '/view/sports'] = array(
		'title' => t('Sports Facilities'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('facilities_view_sports'),
		'access callback' => 'logged_in',
		'file' => 'facilities_list.inc',
		'type' => MENU_LOCAL_TASK,
		'weight' => 2
	);

	$items[FACILITIES_MODULE_NAME . '/view/room/%'] = array(
		'title' => t('Room Information'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('facilities_view_item', 3),
		'access callback' => 'logged_in',
		'file' => 'facilities_item.inc',
		'type' => MENU_CALLBACK
	);

	$items[FACILITIES_MODULE_NAME . '/view/bbq/%'] = array(
		'title' => t('BBQ Pit Information'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('facilities_view_item', 3),
		'access callback' => 'logged_in',
		'file' => 'facilities_item.inc',
		'type' => MENU_CALLBACK
	);

	$items[FACILITIES_MODULE_NAME . '/view/sports/%'] = array(
		'title' => t('Sports Facility Information'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('facilities_view_item', 3),
		'access callback' => 'logged_in',
		'file' => 'facilities_item.inc',
		'type' => MENU_CALLBACK
	);

	$items[FACILITIES_MODULE_NAME . '/edit'] = array(
		'title' => t('Manage Facilities'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('facilities_edit_new'),
		'access callback' => 'is_admin',
		'file' => 'facilities_edit.inc',
		'type' => MENU_NORMAL_ITEM,
	);

	$items[FACILITIES_MODULE_NAME . '/edit/new/bbq'] = array(
		'title' => t('Add New BBQ Pit'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('facilities_edit', 0, BBQ),
		'access callback' => 'is_admin',
		'file' => 'facilities_edit.inc',
		'type' => MENU_LOCAL_ACTION,
	);
	$items[FACILITIES_MODULE_NAME . '/edit/new/sports'] = array(
		'title' => t('Add New Sports Facility'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('facilities_edit', 0, SPORTS),
		'access callback' => 'is_admin',
		'file' => 'facilities_edit.inc',
		'type' => MENU_LOCAL_ACTION,
	);
	$items[FACILITIES_MODULE_NAME . '/edit/new/room'] = array(
		'title' => t('Add New Room'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('facilities_edit', 0, ROOM),
		'access callback' => 'is_admin',
		'file' => 'facilities_edit.inc',
		'type' => MENU_LOCAL_ACTION,
	);
	$items[FACILITIES_MODULE_NAME . '/edit/%'] = array(
		'title' => t('Edit Facility Information'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('facilities_edit', 2),
		'access callback' => 'is_admin',
		'file' => 'facilities_edit.inc',
		'type' => MENU_CALLBACK
	);

	$items[FACILITIES_MODULE_NAME . '/auto_complete_university'] = array(
		'page callback' => 'auto_complete_university',
		'access callback' => true,
		'file' => 'facilities_api.inc',
		'type' => MENU_CALLBACK
	);
	$items[FACILITIES_MODULE_NAME . '/auto_complete_location'] = array(
		'page callback' => 'auto_complete_location',
		'access callback' => true,
		'file' => 'facilities_api.inc',
		'type' => MENU_CALLBACK
	);
	$items[FACILITIES_MODULE_NAME . '/auto_complete_type'] = array(
		'page callback' => 'auto_complete_type',
		'access callback' => true,
		'file' => 'facilities_api.inc',
		'type' => MENU_CALLBACK
	);
	$items[FACILITIES_MODULE_NAME . '/auto_complete_name'] = array(
		'page callback' => 'auto_complete_name',
		'access callback' => true,
		'file' => 'facilities_api.inc',
		'type' => MENU_CALLBACK
	);

	$items['booking/view'] = array(
		'title' => t('Manage Bookings'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('facilities_booking'),
		'access callback' => 'logged_in',
		'file' => 'facilities_booking_list.inc',
		'type' => MENU_NORMAL_ITEM
	);

	$items['booking/edit/%'] = array(
		'title' => t('Manage Bookings'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('facilities_booking_edit', 2),
		'access callback' => 'logged_in',
		'file' => 'facilities_booking_list.inc',
		'type' => MENU_CALLBACK
	);

	$items['booking/delete/%'] = array(
		'title' => t('Delete Bookings'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('facilities_booking_delete', 2),
		'access callback' => 'logged_in',
		'file' => 'facilities_booking_list.inc',
		'type' => MENU_CALLBACK
	);
	return $items;

}